# Author: The Game Master
# Github: ruy223
# Date: 10/02/2026
# Description: Choose your own adventure game

# Classes and Function
from classes_and_functions import print_wrapped


#Menu
answer = input("Would you like to start the game? (yes/no)")
if answer.lower().strip() == "yes":
    print("Welcome to Malikor's Dungeon!")

    #Game background lore
    answer = input("Would you like to hear the backstory? (yes/no)")
    if answer.lower().strip() == "yes":
        print_wrapped("In the shadowed realms of Eldoria, the ancient sorcerer Malikor has risen from centuries of slumber, transforming an abandoned underground fortress into his personal dungeon. A labyrinth of twisted magic, deadly traps, and monstrous guardians. Malikor, once a revered mage who delved too deep into forbidden necromancy, now seeks to harness the ""Heart of Eternity,"" a crystalline artifact buried deep within the dungeon. If he succeeds, he'll unleash an army of undead to conquer the surface world, plunging Eldoria into eternal darkness. Your quest begins after Malikor's minions raid your village and abduct your sister.")
    elif answer.lower().strip() == "no":
        answer = input(print_wrapped("You stand at the crumbling stone entrance of Malikor's Dungeon. The massive archway looms above you, half-swallowed by black vines that pulse faintly, as though breathing. Cracked flagstones underfoot are stained dark—old blood, perhaps, or something worse. A slow, cold wind rises from the throat of the stairwell, carrying the distant sound of dripping water and something that might be a low, wordless moan. Three ways present themselves in the flickering green torchlight: To your left, the main stair descends in a wide, arrogant spiral. The steps are worn smooth by countless feet—some living, most not. Charging down them would announce your arrival like a war horn. Speed, but no secrets. Straight ahead, a jagged crevice splits the wall like a wound. Narrow, damp, barely wide enough for shoulders. It smells of wet stone and old iron. A path for someone who prefers silence over glory, though the darkness inside it feels thicker, hungrier. To your right, the wall is covered in shallow carvings—scenes of robed figures, broken crowns, a single radiant crystal held in skeletal hands. The lines are worn but deliberate; they seem to watch you back. Studying them might cost time, yet something in their geometry promises understanding… or warning. The medallion at your throat grows faintly warm, as though reminding you that Elara is somewhere below. Which path do you take? (left/right/straight)"))
        if answer.lower().strip() == "left":
            print_wrapped("Your heart pounds as you charge down the main stair, boots slamming against stone that has not felt living footsteps in centuries. Each echo rolls back at you like mocking laughter from the dark. The air turns thick and sour, heavy with the stench of rot and old fire. A cold sweat breaks across your skin despite the chill that seeps through your clothes. The stair suddenly levels into a vast grand hall. Vaulted ceilings vanish into blackness above. The floor is a graveyard of shattered armor and rusted weapons that crunch under your boots. Three skeletal guardians rise slowly from the shadows, their bones creaking like dry branches. Emerald fire kindles in their empty eye sockets. Rusted blades scrape free from bony fists. They turn toward the sound of your arrival, hollow voices overlapping in a single rasping whisper: Intruder feed the Heart. Your breath catches. Behind them, half hidden in shadow, a small scrap of blue ribbon flutters on a spike. It is Elaras. You would know it anywhere. The sight sends a sharp pain through your chest, sharper than any blade. The guardians step forward in perfect unison, swords rising, cutting off the only path deeper into the dungeon.Your muscles tense. Your mind races. What do you do? Fight them head on? Try to bluff? Dodge to the side alcove, hoping to slip past? ")
        elif answer.lower().strip() == "right":
            print_wrapped("You turn right and approach the wall covered in ancient carvings. The stone feels unnaturally cool under your fingertips as you trace the shallow lines. Scenes unfold in faded relief: robed figures kneeling before a glowing crystal, crowns shattering on the ground, a lone silhouette standing against a tide of shadow. The final panel shows that same silhouette reaching toward the crystal, fingers almost touching it, face twisted in something between longing and agony. As you study the images, your breathing slows. The medallion at your throat warms again, this time pulsing in time with your heartbeat. The carvings seem to shift subtly when you are not looking directly at them, as though the figures are turning their heads to watch you. A soft click echoes from the wall. One of the stones you touched sinks inward. A narrow panel slides open, revealing a small alcove barely large enough for one person to stand in. Inside rests a single object: a stoppered glass vial filled with a faintly glowing silver liquid. It swirls slowly on its own, like smoke trapped underwater. You lift the vial carefully. The label, etched in an old script you half recognize, reads: Insight's Mercy. Do you drink the liquid? (yes/no)")

        elif answer.lower().strip() == "straight":
            print_wrapped("You turn straight ahead and approach the jagged crevice in the wall. It is barely wide enough for your shoulders. The stone feels damp and slick under your palms as you press through. Darkness swallows you almost at once. The green torchlight from the entrance fades behind you, replaced by a deeper black that presses against your eyes like a living thing. Your footsteps become muffled. The passage narrows further. Your breath sounds unnaturally loud. Something soft and cold brushes your cheek. You freeze. It is only a spiderweb, thick strands clinging to your face and hair. You swipe them away, but your hand comes back wet. Not with water. With something warmer. The metallic scent grows stronger. Blood. Fresh enough that your stomach turns. The crevice widens just enough for you to see a low stone ledge ahead. On it sits a small iron box, lid ajar. Inside lies a silver locket. The same one you gave Elara on her last birthday. The chain is still tangled with a few strands of her dark hair. Your chest tightens. You reach for it. The moment your fingers close around the chain, the floor vanishes. Stone cracks like dry bone. You plummet. The fall is short. The landing is not. You hit the bottom of a narrow pit lined with upward-jutting iron spikes. One spike drives straight through your lower back and out through your stomach. The pain is white-hot, blinding. You cannot scream. Your lungs refuse to fill. Blood fills your mouth in a copper rush. You hang there, impaled, feet dangling inches above the filthy stone floor. The locket slips from your numb fingers and clinks somewhere below you. Above, the crevice entrance is now only a thin slit of dying light. Too high. Too far. A slow scrape echoes from the darkness at the far end of the pit. A skeletal hand reaches into the faint glow, then another. A guardian, smaller than the others but no less precise, crawls forward. Its skull tilts as it studies you. Emerald fire flickers in the sockets. It does not hurry. There is no need. Your vision narrows to a tunnel. The medallion at your throat has gone cold and still. Somewhere far away, you think you hear Elara's voice calling your name, but it is only the blood in your ears. The guardian reaches you. A bony hand closes around your throat. Its grip is gentle, almost careful, as though it does not wish to damage its prize. Your last thought is of the sister you never reached. Darkness takes you")
            print("YOU HAVE DIED. MALIKOR CLAIMS ANOTHER SOUL FOR THE HEART OF ETERNITY")

        else:
            print("Invalid input. You lose!")
                    
    else:
        print("Invalid input. Start again!")

else: print("Maybe next time!")